include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    depend_on_referenced_packages: false
    unrelated_type_equality_checks: false
    use_build_context_synchronously: false
