include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    depend_on_referenced_packages: false
    iterable_contains_unrelated_type: false
    library_private_types_in_public_api: false
    unrelated_type_equality_checks: false
    use_build_context_synchronously: false
