name: senha_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  favicon: ^1.1.1
  firebase_auth: ^4.6.2
  firebase_ui_firestore: ^1.5.2
  firebase_core: ^2.13.1
  flutter_list_view: ^1.1.21
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^2.0.6
  flutter_switch: ^0.3.2
  google_sign_in: ^6.1.3
  go_router: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  skeleton_animation: ^0.1.4
  styled_text: ^7.0.0
  unicons: ^2.1.1
  uuid: ^3.0.7
  toastification: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/icons/
    - assets/images/

  fonts:
    - family: duolingo
      fonts:
        - asset: assets/fonts/duolingo.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
